### ISSUE TITLE
Introduce new utility MoreFiles#listRecursiveFilesInDirectory

### ISSUE THREAD

**Issue by jonsyu1** [palantir/giraffe#34]
We want a utility method for recursively listing the files in a directory, returning a flattened list of `Path`s. I'm not sure what kind of contract we want to use for the list: I would default to appending file `Path`s to the list as we recurisvely traverse the `DirectoryStream` unless anyone has a preference.

**Comment by bluekeyes** [comment]
PRs welcome. I'm currently thinking 0.7.1 will be released at the end of this week, so if you have time, it would probably be good to get it in before then.

**Comment by jonsyu1** [comment]
great, I'll see if I have time. Otherwise, I'll ask David Karesh to look into this as a post-merge task.

**Comment by jonsyu1** [comment]
https://github.com/palantir/giraffe/pull/42

**Comment by jonsyu1** [comment]
Ah sorry, I forgot to close this
