### ISSUE TITLE
404 in the latest javadoc

### ISSUE THREAD

**Issue by feeblefakie** [palantir/giraffe#87]
I found some 404 in the latest javadoc of version 0.10.
https://palantir.github.io/giraffe/docs/0.10.0/api/index.html

If you click `PasswordSshCredential` from the left down pane, you get 404.
https://palantir.github.io/giraffe/docs/0.10.0/api/com/palantir/giraffe/ssh/PasswordSshCredential.html

Many links are also not working.
Please check it out.

**Comment by bluekeyes** [comment]
Thanks for catching this. Due to a `.gitignore` issue, all documentation for the `ssh` package was excluded from the GitHub Pages build. I've fixed this and added the `ssh` package back to the 0.10.0 and 0.9.0 documentation.
